INSERT INTO daily_tasks (daily_tasks_name, jscope_path, category, task_order, processed) VALUES
('ADRs – Architecture Decision Records', 'adrs-architecture-decision-records', 'agile-arbeitsweise', 1, false),
('Backlog Refinement', 'backlog-refinement', 'agile-arbeitsweise', 2, false),
('Code Reviews – Worauf achten?', 'code-reviews-worauf-achten', 'agile-arbeitsweise', 3, false),
('Definition of Done', 'definition-of-done', 'agile-arbeitsweise', 4, false),
('Definition of Ready', 'definition-of-ready', 'agile-arbeitsweise', 5, false),
('Feature Flags', 'feature-flags', 'agile-arbeitsweise', 6, false),
('Kanban Grundlagen', 'kanban-grundlagen', 'agile-arbeitsweise', 7, false),
('Pair Programming', 'pair-programming', 'agile-arbeitsweise', 8, false),
('Scrum Grundlagen', 'scrum-grundlagen', 'agile-arbeitsweise', 9, false),
('Sprint, Planning, Daily, Retro & Review', 'sprint-planning-daily-retro-review', 'agile-arbeitsweise', 10, false),
('Story Points & Estimation', 'story-points-estimation', 'agile-arbeitsweise', 11, false),
('Technische Schuld (Tech Debt)', 'technische-schuld-tech-debt', 'agile-arbeitsweise', 12, false),
('Timeboxing', 'timeboxing', 'agile-arbeitsweise', 13, false),
('Trunk-Based Development vs. Git Flow', 'trunk-based-development-vs-git-flow', 'agile-arbeitsweise', 14, false),
('User Stories & Acceptance Criteria', 'user-stories-acceptance-criteria', 'agile-arbeitsweise', 15, false),
('Arrays', 'arrays', 'algorithmen-datenstrukturen-grundlagen', 16, false),
('Big-O Notation', 'big-o-notation', 'algorithmen-datenstrukturen-grundlagen', 17, false),
('DFS & BFS', 'dfs-bfs', 'algorithmen-datenstrukturen-grundlagen', 18, false),
('Graphs Grundlagen', 'graphs-grundlagen', 'algorithmen-datenstrukturen-grundlagen', 19, false),
('HashMaps & HashSets – Intern', 'hashmaps-hashsets-intern', 'algorithmen-datenstrukturen-grundlagen', 20, false),
('Linked Lists', 'linked-lists', 'algorithmen-datenstrukturen-grundlagen', 21, false),
('Recursion', 'recursion', 'algorithmen-datenstrukturen-grundlagen', 22, false),
('Searching – Linear & Binary Search', 'searching-linear-binary-search', 'algorithmen-datenstrukturen-grundlagen', 23, false),
('Sliding Window Technik', 'sliding-window', 'algorithmen-datenstrukturen-grundlagen', 24, false),
('Sorting – Bubble, Quick, Merge & Insertion', 'sorting-bubble-quick-merge-insertion', 'algorithmen-datenstrukturen-grundlagen', 25, false),
('Stacks & Queues', 'stacks-queues', 'algorithmen-datenstrukturen-grundlagen', 26, false),
('Trees – Binary Tree & BST', 'trees-binary-tree-bst', 'algorithmen-datenstrukturen-grundlagen', 27, false),
('Two-Pointer Technik', 'two-pointer-technik', 'algorithmen-datenstrukturen-grundlagen', 28, false),
('Wann welche Datenstruktur?', 'wann-welche-datenstruktur', 'algorithmen-datenstrukturen-grundlagen', 29, false),
('API Authentication – API Keys, OAuth2 & JWT', 'api-authentication-api-keys-oauth2-jwt', 'api-design-kommunikation', 30, false),
('API Backward Compatibility', 'api-backward-compatibility', 'api-design-kommunikation', 31, false),
('API Dokumentation – OpenAPI & Swagger', 'api-dokumentation-openapi-swagger', 'api-design-kommunikation', 32, false),
('API Rate Limiting', 'api-rate-limiting', 'api-design-kommunikation', 33, false),
('Error Response Design', 'error-response-design', 'api-design-kommunikation', 34, false),
('GraphQL Grundlagen', 'graphql-grundlagen', 'api-design-kommunikation', 35, false),
('gRPC Grundlagen', 'grpc-grundlagen', 'api-design-kommunikation', 36, false),
('HTTP Methoden & Idempotenz', 'http-methoden-idempotenz', 'api-design-kommunikation', 37, false),
('HTTP Statuscodes – 2xx, 3xx, 4xx, 5xx', 'http-statuscodes', 'api-design-kommunikation', 38, false),
('Idempotency Keys', 'idempotency-keys', 'api-design-kommunikation', 39, false),
('Request/Response Body Design', 'request-response-body-design', 'api-design-kommunikation', 40, false),
('REST Prinzipien – Stateless, Uniform Interface usw.', 'rest-prinzipien', 'api-design-kommunikation', 41, false),
('Semantic Versioning', 'semantic-versioning', 'api-design-kommunikation', 42, false),
('Server-Sent Events (SSE)', 'server-sent-events-sse', 'api-design-kommunikation', 43, false),
('Webhooks', 'webhooks', 'api-design-kommunikation', 44, false),
('WebSockets', 'websockets', 'api-design-kommunikation', 45, false),
('12-Factor App', '12-factor-app', 'architektur', 46, false),
('Aggregate (DDD)', 'aggregate', 'architektur', 47, false),
('API Gateway Pattern', 'api-gateway-pattern', 'architektur', 48, false),
('At-Least-Once vs. At-Most-Once vs. Exactly-Once Delivery', 'at-least-once-vs-exactly-once', 'architektur', 49, false),
('Backend for Frontend (BFF) Pattern', 'backend-for-frontend-bff-pattern', 'architektur', 50, false),
('Backpressure', 'backpressure', 'architektur', 51, false),
('Bounded Context', 'bounded-context', 'architektur', 52, false),
('Cache Invalidation', 'cache-invalidation', 'architektur', 53, false),
('Cache Stampede & Thundering Herd', 'cache-stampede-thundering-herd', 'architektur', 54, false),
('Cache Strategien – Cache-Aside, Write-Through, Write-Behind', 'cache-strategien', 'architektur', 55, false),
('Clean Architecture', 'clean-architecture', 'architektur', 56, false),
('CQRS – Command Query Responsibility Segregation', 'cqrs', 'architektur', 57, false),
('Dead Letter Queue', 'dead-letter-queue', 'architektur', 58, false),
('Distributed Caching', 'distributed-caching', 'architektur', 59, false),
('Domain Driven Design (DDD) Grundlagen', 'domain-driven-design-grundlagen', 'architektur', 60, false),
('Domain Events', 'domain-events', 'architektur', 61, false),
('Entity vs. Value Object', 'entity-vs-value-object', 'architektur', 62, false),
('Event-Driven Architecture', 'event-driven-architecture', 'architektur', 63, false),
('Event Schema Evolution – Avro & Schema Registry', 'event-schema-evolution', 'architektur', 64, false),
('Event Sourcing', 'event-sourcing', 'architektur', 65, false),
('Hexagonale Architektur (Ports & Adapters)', 'hexagonale-architektur', 'architektur', 66, false),
('Idempotenz bei Message Processing', 'idempotenz-message-processing', 'architektur', 67, false),
('Kafka Connect', 'kafka-connect', 'architektur', 68, false),
('Kafka Consumer Groups', 'kafka-consumer-groups', 'architektur', 69, false),
('Kafka Grundlagen', 'kafka-grundlagen', 'architektur', 70, false),
('Kafka Offset Management', 'kafka-offset-management', 'architektur', 71, false),
('Kafka Partitions', 'kafka-partitions', 'architektur', 72, false),
('Kafka Producers', 'kafka-producers', 'architektur', 73, false),
('Kafka Streams Grundlagen', 'kafka-streams-grundlagen', 'architektur', 74, false),
('Kafka Topics', 'kafka-topics', 'architektur', 75, false),
('Kafka vs. RabbitMQ', 'kafka-vs-rabbitmq', 'architektur', 76, false),
('Layered Architecture – Controller, Service, Repository', 'layered-architecture', 'architektur', 77, false),
('Modularer Monolith', 'modularer-monolith', 'architektur', 78, false),
('Monolith vs. Microservices', 'monolith-vs-microservices', 'architektur', 79, false),
('Onion Architecture', 'onion-architecture', 'architektur', 80, false),
('Ordering Guarantees in Kafka', 'ordering-guarantees-kafka', 'architektur', 81, false),
('Redis als Cache', 'redis-als-cache', 'architektur', 82, false),
('REST vs. gRPC vs. GraphQL', 'rest-vs-grpc-vs-graphql', 'architektur', 83, false),
('Sidecar Pattern', 'sidecar-pattern', 'architektur', 84, false),
('Spring Cache Abstraction – @Cacheable, @CacheEvict', 'spring-cache-abstraction', 'architektur', 85, false),
('Spring Kafka – @KafkaListener & KafkaTemplate', 'spring-kafka', 'architektur', 86, false),
('Strangler Fig Pattern (Migration)', 'strangler-fig-pattern', 'architektur', 87, false),
('Synchrone vs. Asynchrone Kommunikation', 'synchrone-vs-asynchrone-kommunikation', 'architektur', 88, false),
('TTL – Time to Live', 'ttl-time-to-live', 'architektur', 89, false),
('Ubiquitous Language', 'ubiquitous-language', 'architektur', 90, false),
('Vor- und Nachteile von Microservices', 'vor-nachteile-microservices', 'architektur', 91, false),
('Wann Monolith, wann Microservices?', 'wann-monolith-wann-microservices', 'architektur', 92, false),
('Warum Caching?', 'warum-caching', 'architektur', 93, false),
('Warum Message Broker?', 'warum-message-broker', 'architektur', 94, false),
('BOM – Bill of Materials', 'bom-bill-of-materials', 'build-tools-dependency-management', 95, false),
('Dependency Conflicts lösen', 'dependency-conflicts-loesen', 'build-tools-dependency-management', 96, false),
('Gradle Grundlagen', 'gradle-grundlagen', 'build-tools-dependency-management', 97, false),
('Gradle vs. Maven', 'gradle-vs-maven', 'build-tools-dependency-management', 98, false),
('Maven Dependency Scopes – compile, test, runtime, provided', 'maven-dependency-scopes', 'build-tools-dependency-management', 99, false),
('Maven Grundlagen', 'maven-grundlagen', 'build-tools-dependency-management', 100, false),
('Maven Lifecycle – clean, compile, test, package, install, deploy', 'maven-lifecycle', 'build-tools-dependency-management', 101, false),
('Maven Multi-Module Projects', 'maven-multi-module', 'build-tools-dependency-management', 102, false),
('Maven Profiles', 'maven-profiles', 'build-tools-dependency-management', 103, false),
('Maven Wrapper & Gradle Wrapper', 'maven-wrapper', 'build-tools-dependency-management', 104, false),
('pom.xml Struktur', 'pom-xml-struktur', 'build-tools-dependency-management', 105, false),
('Automatisierte Tests in der Pipeline', 'automatisierte-tests-pipeline', 'ci-cd-devops', 106, false),
('Build Pipeline Grundlagen', 'build-pipeline-grundlagen', 'ci-cd-devops', 107, false),
('Code Quality Gates', 'code-quality-gates', 'ci-cd-devops', 108, false),
('Deployment Strategien – Blue-Green, Canary, Rolling', 'deployment-strategien', 'ci-cd-devops', 109, false),
('Environment Variables & Secrets Management', 'environment-variables-secrets', 'ci-cd-devops', 110, false),
('GitHub Actions Grundlagen', 'github-actions-grundlagen', 'ci-cd-devops', 111, false),
('GitLab CI Grundlagen', 'gitlab-ci-grundlagen', 'ci-cd-devops', 112, false),
('Infrastructure as Code Grundlagen', 'infrastructure-as-code', 'ci-cd-devops', 113, false),
('Jenkins Grundlagen', 'jenkins-grundlagen', 'ci-cd-devops', 114, false),
('Pipeline Stages – Build, Test, Lint, Deploy', 'pipeline-stages', 'ci-cd-devops', 115, false),
('Static Code Analysis – SonarQube, Checkstyle, SpotBugs', 'static-code-analysis', 'ci-cd-devops', 116, false),
('Was ist CI/CD?', 'was-ist-ci-cd', 'ci-cd-devops', 117, false),
('Aussagekräftige Variablen- und Methodennamen', 'aussagekraeftige-namen', 'clean-code', 118, false),
('Boy Scout Rule', 'boy-scout-rule', 'clean-code', 119, false),
('Code Smells erkennen', 'code-smells-erkennen', 'clean-code', 120, false),
('Data Clumps', 'data-clumps', 'clean-code', 121, false),
('Dead Code entfernen', 'dead-code-entfernen', 'clean-code', 122, false),
('Defensive Kopien', 'defensive-kopien', 'clean-code', 123, false),
('Divergent Change', 'divergent-change', 'clean-code', 124, false),
('Fail Fast Principle', 'fail-fast-principle', 'clean-code', 125, false),
('Feature Envy', 'feature-envy', 'clean-code', 126, false),
('God Class', 'god-class', 'clean-code', 127, false),
('Guard Clauses & Early Returns', 'guard-clauses-early-returns', 'clean-code', 128, false),
('Immutability bevorzugen', 'immutability-bevorzugen', 'clean-code', 129, false),
('Keine auskommentierten Codeblöcke', 'keine-auskommentierten-codeblöcke', 'clean-code', 130, false),
('Keine Magic Numbers & Magic Strings', 'keine-magic-numbers', 'clean-code', 131, false),
('Keine verschachtelten if-else-Kaskaden', 'keine-verschachtelten-if-else', 'clean-code', 132, false),
('Kommentare: Warum, nicht Was', 'kommentare-warum-nicht-was', 'clean-code', 133, false),
('Konsistente Formatierung', 'konsistente-formatierung', 'clean-code', 134, false),
('Konstanten statt hardcoded Values', 'konstanten-statt-hardcoded', 'clean-code', 135, false),
('Long Method (Code Smell)', 'long-method', 'clean-code', 136, false),
('Methoden: Eine Aufgabe, eine Abstraktionsebene', 'methoden-eine-aufgabe', 'clean-code', 137, false),
('Methoden kurz halten', 'methoden-kurz-halten', 'clean-code', 138, false),
('Null vermeiden – Optional nutzen', 'null-vermeiden-optional', 'clean-code', 139, false),
('Package-Struktur sinnvoll aufbauen', 'package-struktur-aufbauen', 'clean-code', 140, false),
('Primitive Obsession', 'primitive-obsession', 'clean-code', 141, false),
('Shotgun Surgery', 'shotgun-surgery', 'clean-code', 142, false),
('Single Responsibility auf Methodenebene', 'single-responsibility-methode', 'clean-code', 143, false),
('Collections – unmodifiableList, Map, Set', 'collections-unmodifiable', 'collections-framework', 144, false),
('Comparable vs. Comparator', 'comparable-vs-comparator', 'collections-framework', 145, false),
('Concurrent Collections – CopyOnWriteArrayList & BlockingQueue', 'concurrent-collections', 'collections-framework', 146, false),
('ConcurrentHashMap', 'concurrenthashmap', 'collections-framework', 147, false),
('Deque', 'deque', 'collections-framework', 148, false),
('EnumSet & EnumMap', 'enumset-enummap', 'collections-framework', 149, false),
('equals() & hashCode() Vertrag', 'equals-hashcode-vertrag', 'collections-framework', 150, false),
('Fail-Fast vs. Fail-Safe Iteratoren', 'fail-fast-vs-fail-safe', 'collections-framework', 151, false),
('Hash Collisions & Collision Resolution', 'hash-collisions', 'collections-framework', 152, false),
('HashMap Internals – Buckets, Hashing & Rehashing', 'hashmap-internals', 'collections-framework', 153, false),
('Iterable Interface', 'iterable-interface', 'collections-framework', 154, false),
('Iterator vs. ListIterator', 'iterator-vs-listiterator', 'collections-framework', 155, false),
('List – ArrayList, LinkedList, Vector, Stack', 'list-arraylist-linkedlist', 'collections-framework', 156, false),
('List.of(), Map.of(), Set.of() – Immutable Collections', 'list-of-map-of-set-of', 'collections-framework', 157, false),
('Map – HashMap, LinkedHashMap, TreeMap, Hashtable', 'map-hashmap-treemap', 'collections-framework', 158, false),
('NavigableMap & NavigableSet', 'navigablemap-navigableset', 'collections-framework', 159, false),
('Queue – PriorityQueue & ArrayDeque', 'queue-priorityqueue', 'collections-framework', 160, false),
('Set – HashSet, LinkedHashSet, TreeSet', 'set-hashset-treeset', 'collections-framework', 161, false),
('WeakHashMap', 'weakhashmap', 'collections-framework', 162, false),
('ACID Prinzipien', 'acid-prinzipien', 'datenbanken-sql', 163, false),
('Aggregatfunktionen – COUNT, SUM, AVG, MIN, MAX', 'aggregatfunktionen', 'datenbanken-sql', 164, false),
('Composite Indizes', 'composite-indizes', 'datenbanken-sql', 165, false),
('Connection Pooling & HikariCP', 'connection-pooling-hikaricp', 'datenbanken-sql', 166, false),
('Denormalisierung – Wann sinnvoll?', 'denormalisierung', 'datenbanken-sql', 167, false),
('GROUP BY & HAVING', 'group-by-having', 'datenbanken-sql', 168, false),
('Indizes – B-Tree & Hash', 'indizes-b-tree-hash', 'datenbanken-sql', 169, false),
('Isolation Levels in der Datenbank', 'isolation-levels', 'datenbanken-sql', 170, false),
('Joins – INNER, LEFT, RIGHT, FULL, CROSS', 'joins', 'datenbanken-sql', 171, false),
('MongoDB Grundlagen', 'mongodb-grundlagen', 'datenbanken-sql', 172, false),
('Normalisierung – 1NF, 2NF, 3NF', 'normalisierung-1nf-2nf-3nf', 'datenbanken-sql', 173, false),
('NoSQL Grundlagen – Document, Key-Value, Column, Graph', 'nosql-grundlagen', 'datenbanken-sql', 174, false),
('PostgreSQL Features – JSONB, CTEs, Window Functions', 'postgresql-spezifische-features', 'datenbanken-sql', 175, false),
('Query Execution Plan lesen (EXPLAIN)', 'query-execution-plan', 'datenbanken-sql', 176, false),
('Redis – Caching & Session Store', 'redis-caching-session', 'datenbanken-sql', 177, false),
('SQL Grundlagen – SELECT, INSERT, UPDATE, DELETE', 'sql-grundlagen', 'datenbanken-sql', 178, false),
('SQL vs. NoSQL – Wann was?', 'sql-vs-nosql', 'datenbanken-sql', 179, false),
('Stored Procedures', 'stored-procedures', 'datenbanken-sql', 180, false),
('Subqueries', 'subqueries', 'datenbanken-sql', 181, false),
('Transactions (Datenbank)', 'transactions-db', 'datenbanken-sql', 182, false),
('Triggers', 'triggers', 'datenbanken-sql', 183, false),
('UNION vs. UNION ALL', 'union-vs-union-all', 'datenbanken-sql', 184, false),
('Views', 'views', 'datenbanken-sql', 185, false),
('Wann Indizes sinnvoll sind – und wann nicht', 'wann-indizes-sinnvoll', 'datenbanken-sql', 186, false),
('Abstract Factory Pattern', 'abstract-factory', 'design-patterns', 187, false),
('Adapter Pattern', 'adapter', 'design-patterns', 188, false),
('Bridge Pattern', 'bridge', 'design-patterns', 189, false),
('Builder Pattern', 'builder', 'design-patterns', 190, false),
('Bulkhead Pattern', 'bulkhead-pattern', 'design-patterns', 191, false),
('Chain of Responsibility', 'chain-of-responsibility', 'design-patterns', 192, false),
('Circuit Breaker Pattern', 'circuit-breaker', 'design-patterns', 193, false),
('Command Pattern', 'command', 'design-patterns', 194, false),
('Composite Pattern', 'composite', 'design-patterns', 195, false),
('CQRS Pattern', 'cqrs-pattern', 'design-patterns', 196, false),
('DAO Pattern – Data Access Object', 'dao-pattern', 'design-patterns', 197, false),
('Decorator Pattern', 'decorator', 'design-patterns', 198, false),
('Dependency Injection Pattern', 'dependency-injection-pattern', 'design-patterns', 199, false),
('DTO Pattern – Data Transfer Object', 'dto-pattern', 'design-patterns', 200, false),
('Event-Driven Pattern', 'event-driven-pattern', 'design-patterns', 201, false),
('Facade Pattern', 'facade', 'design-patterns', 202, false),
('Factory Method Pattern', 'factory-method', 'design-patterns', 203, false),
('Flyweight Pattern', 'flyweight', 'design-patterns', 204, false),
('Iterator Pattern', 'iterator-pattern', 'design-patterns', 205, false),
('Mediator Pattern', 'mediator', 'design-patterns', 206, false),
('MVC Pattern', 'mvc-pattern', 'design-patterns', 207, false),
('Observer Pattern', 'observer', 'design-patterns', 208, false),
('Outbox Pattern', 'outbox-pattern', 'design-patterns', 209, false),
('Prototype Pattern', 'prototype', 'design-patterns', 210, false),
('Proxy Pattern', 'proxy', 'design-patterns', 211, false),
('Repository Pattern', 'repository-pattern', 'design-patterns', 212, false),
('Retry Pattern', 'retry-pattern', 'design-patterns', 213, false),
('Saga Pattern', 'saga-pattern', 'design-patterns', 214, false),
('Service Layer Pattern', 'service-layer-pattern', 'design-patterns', 215, false),
('Singleton Pattern', 'singleton', 'design-patterns', 216, false),
('State Pattern', 'state', 'design-patterns', 217, false),
('Strategy Pattern', 'strategy', 'design-patterns', 218, false),
('Template Method Pattern', 'template-method', 'design-patterns', 219, false),
('Visitor Pattern', 'visitor', 'design-patterns', 220, false),
('Container Registries – Docker Hub & GHCR', 'container-registries', 'docker-containerisierung', 221, false),
('Container vs. VM', 'container-vs-vm', 'docker-containerisierung', 222, false),
('Docker Best Practices – Kleine Images, Non-Root User', 'docker-best-practices', 'docker-containerisierung', 223, false),
('Docker Compose', 'docker-compose', 'docker-containerisierung', 224, false),
('Docker Grundlagen', 'docker-grundlagen', 'docker-containerisierung', 225, false),
('Docker Images – Base Image & Layer Cache', 'docker-images', 'docker-containerisierung', 226, false),
('Docker Networking', 'docker-networking', 'docker-containerisierung', 227, false),
('Docker Volumes', 'docker-volumes', 'docker-containerisierung', 228, false),
('Dockerfile schreiben', 'dockerfile-schreiben', 'docker-containerisierung', 229, false),
('.dockerignore', 'dockerignore', 'docker-containerisierung', 230, false),
('Health Checks in Docker', 'health-checks-docker', 'docker-containerisierung', 231, false),
('Multi-Stage Builds', 'multi-stage-builds', 'docker-containerisierung', 232, false),
('AutoCloseable Interface', 'autocloseable-interface', 'exception-handling', 233, false),
('Best Practices – Keine leeren Catch-Blöcke, spezifische Exceptions', 'best-practices-exceptions', 'exception-handling', 234, false),
('Checked vs. Unchecked Exceptions', 'checked-vs-unchecked', 'exception-handling', 235, false),
('Custom Exceptions', 'custom-exceptions', 'exception-handling', 236, false),
('Error vs. Exception', 'error-vs-exception', 'exception-handling', 237, false),
('Exception Chaining', 'exception-chaining', 'exception-handling', 238, false),
('Multi-Catch', 'multi-catch', 'exception-handling', 239, false),
('Stacktrace lesen und verstehen', 'stacktrace-lesen', 'exception-handling', 240, false),
('try-catch-finally', 'try-catch-finally', 'exception-handling', 241, false),
('try-with-resources', 'try-with-resources', 'exception-handling', 242, false),
('Warum keine Exceptions für Flow Control?', 'keine-exceptions-flow-control', 'exception-handling', 243, false),
('Collectors – toList, toMap, groupingBy, partitioningBy, joining', 'collectors', 'functional-programming-streams', 244, false),
('Functional Interfaces – Predicate, Function, Consumer, Supplier', 'functional-interfaces', 'functional-programming-streams', 245, false),
('Intermediate Operations – map, filter, flatMap, peek, sorted', 'intermediate-operations', 'functional-programming-streams', 246, false),
('Lambda Expressions', 'lambda-expressions', 'functional-programming-streams', 247, false),
('Lazy Evaluation in Streams', 'lazy-evaluation-streams', 'functional-programming-streams', 248, false),
('Method References', 'method-references', 'functional-programming-streams', 249, false),
('Optional Best Practices', 'optional-best-practices', 'functional-programming-streams', 250, false),
('Optional', 'optional', 'functional-programming-streams', 251, false),
('Parallel Streams – Gefahren & wann sinnvoll', 'parallel-streams-gefahren', 'functional-programming-streams', 252, false),
('Parallel Streams', 'parallel-streams', 'functional-programming-streams', 253, false),
('Short-Circuiting Operations', 'short-circuiting', 'functional-programming-streams', 254, false),
('Stream API', 'stream-api', 'functional-programming-streams', 255, false),
('Stream.of() vs. Arrays.stream()', 'stream-of-vs-arrays-stream', 'functional-programming-streams', 256, false),
('Stream vs. Collection', 'stream-vs-collection', 'functional-programming-streams', 257, false),
('Terminal Operations – collect, forEach, reduce, count, findFirst', 'terminal-operations', 'functional-programming-streams', 258, false),
('Bounded Type Parameters – extends & super', 'bounded-type-parameters', 'generics', 259, false),
('Diamond Operator', 'diamond-operator', 'generics', 260, false),
('Generics vs. Raw Types', 'generics-vs-raw-types', 'generics', 261, false),
('Generische Klassen', 'generische-klassen', 'generics', 262, false),
('Generische Methoden', 'generische-methoden', 'generics', 263, false),
('PECS Prinzip – Producer Extends, Consumer Super', 'pecs-prinzip', 'generics', 264, false),
('Type Erasure', 'type-erasure', 'generics', 265, false),
('Wildcards – extends & super', 'wildcards', 'generics', 266, false),
('Eigene Projekte & Entscheidungen erklären können', 'eigene-projekte-erklaeren', 'interview-spezifische-soft-topics', 267, false),
('Java vs. C#', 'java-vs-c', 'interview-spezifische-soft-topics', 268, false),
('Java vs. Kotlin', 'java-vs-kotlin', 'interview-spezifische-soft-topics', 269, false),
('Java vs. Python – Wann was?', 'java-vs-python', 'interview-spezifische-soft-topics', 270, false),
('Komplexe Themen einfach erklären können', 'komplexe-themen-einfach-erklaeren', 'interview-spezifische-soft-topics', 271, false),
('Technische Entscheidungen begründen können', 'technische-entscheidungen-begruenden', 'interview-spezifische-soft-topics', 272, false),
('Trade-offs erklären können', 'trade-offs-erklaeren', 'interview-spezifische-soft-topics', 273, false),
('Warum CI/CD?', 'warum-ci-cd', 'interview-spezifische-soft-topics', 274, false),
('Warum Clean Code?', 'warum-clean-code', 'interview-spezifische-soft-topics', 275, false),
('Warum Docker?', 'warum-docker', 'interview-spezifische-soft-topics', 276, false),
('Warum Java?', 'warum-java', 'interview-spezifische-soft-topics', 277, false),
('Warum Kafka?', 'warum-kafka', 'interview-spezifische-soft-topics', 278, false),
('Warum Kubernetes?', 'warum-kubernetes', 'interview-spezifische-soft-topics', 279, false),
('Warum Microservices?', 'warum-microservices', 'interview-spezifische-soft-topics', 280, false),
('Warum OOP?', 'warum-oop', 'interview-spezifische-soft-topics', 281, false),
('Warum REST?', 'warum-rest', 'interview-spezifische-soft-topics', 282, false),
('Warum Spring Boot?', 'warum-spring-boot', 'interview-spezifische-soft-topics', 283, false),
('Warum Testen?', 'warum-testen', 'interview-spezifische-soft-topics', 284, false),
('Annotations – Built-in & Custom', 'annotations-built-in-custom', 'java-grundlagen', 285, false),
('Arrays vs. ArrayList', 'arrays-vs-arraylist', 'java-grundlagen', 286, false),
('Autoboxing & Unboxing', 'autoboxing-unboxing', 'java-grundlagen', 287, false),
('ClassLoader Hierarchie', 'classloader-hierarchie', 'java-grundlagen', 288, false),
('Enums', 'enums', 'java-grundlagen', 289, false),
('final Keyword – Variablen, Methoden, Klassen', 'final-keyword', 'java-grundlagen', 290, false),
('Garbage Collection Grundlagen', 'garbage-collection-grundlagen', 'java-grundlagen', 291, false),
('Garbage Collector Typen – G1, ZGC, Shenandoah', 'garbage-collector-typen', 'java-grundlagen', 292, false),
('Java Module System (JPMS)', 'java-module-system', 'java-grundlagen', 293, false),
('JDK vs. JRE vs. JVM', 'jdk-vs-jre-vs-jvm', 'java-grundlagen', 294, false),
('JVM Architektur – JIT, Bytecode & Class Loading', 'jvm-architektur', 'java-grundlagen', 295, false),
('Memory Leaks erkennen und vermeiden', 'memory-leaks', 'java-grundlagen', 296, false),
('Operators & Operator Precedence', 'operators-precedence', 'java-grundlagen', 297, false),
('Pass-by-Value vs. Pass-by-Reference in Java', 'pass-by-value', 'java-grundlagen', 298, false),
('Pattern Matching – instanceof & switch', 'pattern-matching', 'java-grundlagen', 299, false),
('Primitive Datentypen vs. Referenztypen', 'primitive-vs-referenztypen', 'java-grundlagen', 300, false),
('Records (Java 16+)', 'records', 'java-grundlagen', 301, false),
('Reflection API', 'reflection-api', 'java-grundlagen', 302, false),
('Sealed Classes', 'sealed-classes', 'java-grundlagen', 303, false),
('Stack vs. Heap Memory', 'stack-vs-heap', 'java-grundlagen', 304, false),
('Static Imports', 'static-imports', 'java-grundlagen', 305, false),
('String Pool & String Immutability', 'string-pool-immutability', 'java-grundlagen', 306, false),
('StringBuilder vs. StringBuffer', 'stringbuilder-vs-stringbuffer', 'java-grundlagen', 307, false),
('Switch Expressions (Java 14+)', 'switch-expressions', 'java-grundlagen', 308, false),
('Ternary Operator', 'ternary-operator', 'java-grundlagen', 309, false),
('Text Blocks', 'text-blocks', 'java-grundlagen', 310, false),
('transient Keyword', 'transient-keyword', 'java-grundlagen', 311, false),
('Type Casting – Implicit & Explicit', 'type-casting', 'java-grundlagen', 312, false),
('var – Local Variable Type Inference', 'var-type-inference', 'java-grundlagen', 313, false),
('Varargs', 'varargs', 'java-grundlagen', 314, false),
('volatile Keyword', 'volatile-keyword', 'java-grundlagen', 315, false),
('ArchUnit', 'archunit', 'java-oekosystem-tooling', 316, false),
('Checkstyle, PMD & SpotBugs', 'checkstyle-pmd-spotbugs', 'java-oekosystem-tooling', 317, false),
('Debugging in IntelliJ', 'debugging-intellij', 'java-oekosystem-tooling', 318, false),
('Feign Client', 'feign-client', 'java-oekosystem-tooling', 319, false),
('Heap Dumps analysieren', 'heap-dumps', 'java-oekosystem-tooling', 320, false),
('IntelliJ IDEA Shortcuts & Productivity', 'intellij-shortcuts', 'java-oekosystem-tooling', 321, false),
('Jackson – JSON Serialization & Deserialization', 'jackson', 'java-oekosystem-tooling', 322, false),
('@JsonProperty, @JsonIgnore, @JsonFormat', 'jsonproperty-jsonignore', 'java-oekosystem-tooling', 323, false),
('Lombok', 'lombok', 'java-oekosystem-tooling', 324, false),
('MapStruct', 'mapstruct', 'java-oekosystem-tooling', 325, false),
('Micrometer', 'micrometer', 'java-oekosystem-tooling', 326, false),
('Profiling – VisualVM, JFR & Async Profiler', 'profiling-visualvm', 'java-oekosystem-tooling', 327, false),
('Remote Debugging', 'remote-debugging', 'java-oekosystem-tooling', 328, false),
('RestClient, WebClient & RestTemplate', 'restclient-webclient-resttemplate', 'java-oekosystem-tooling', 329, false),
('SonarQube', 'sonarqube', 'java-oekosystem-tooling', 330, false),
('Testcontainers', 'testcontainers-tooling', 'java-oekosystem-tooling', 331, false),
('Thread Dumps lesen', 'thread-dumps-lesen', 'java-oekosystem-tooling', 332, false),
('WireMock', 'wiremock-tooling', 'java-oekosystem-tooling', 333, false),
('ConfigMaps & Secrets', 'configmaps-secrets', 'kubernetes-grundlagen', 334, false),
('Deployments (K8s)', 'deployments-k8s', 'kubernetes-grundlagen', 335, false),
('Helm Charts Grundlagen', 'helm-charts', 'kubernetes-grundlagen', 336, false),
('Horizontal Pod Autoscaler', 'horizontal-pod-autoscaler', 'kubernetes-grundlagen', 337, false),
('Ingress', 'ingress', 'kubernetes-grundlagen', 338, false),
('kubectl Grundbefehle', 'kubectl-grundbefehle', 'kubernetes-grundlagen', 339, false),
('Liveness & Readiness Probes', 'liveness-readiness-probes', 'kubernetes-grundlagen', 340, false),
('Namespaces', 'namespaces', 'kubernetes-grundlagen', 341, false),
('Pods', 'pods', 'kubernetes-grundlagen', 342, false),
('Services – ClusterIP, NodePort, LoadBalancer', 'services-k8s', 'kubernetes-grundlagen', 343, false),
('Warum Kubernetes?', 'warum-kubernetes', 'kubernetes-grundlagen', 344, false),
('Alerting Grundlagen', 'alerting-grundlagen', 'logging-monitoring-observability', 345, false),
('Correlation IDs', 'correlation-ids', 'logging-monitoring-observability', 346, false),
('Distributed Tracing – Zipkin & Jaeger', 'distributed-tracing', 'logging-monitoring-observability', 347, false),
('ELK Stack – Elasticsearch, Logstash, Kibana', 'elk-stack', 'logging-monitoring-observability', 348, false),
('Log Levels – TRACE, DEBUG, INFO, WARN, ERROR', 'log-levels', 'logging-monitoring-observability', 349, false),
('Logging Best Practices', 'logging-best-practices', 'logging-monitoring-observability', 350, false),
('MDC – Mapped Diagnostic Context', 'mdc-mapped-diagnostic-context', 'logging-monitoring-observability', 351, false),
('Micrometer Metrics', 'micrometer-metrics', 'logging-monitoring-observability', 352, false),
('Prometheus & Grafana', 'prometheus-grafana', 'logging-monitoring-observability', 353, false),
('SLF4J & Logback Konfiguration', 'slf4j-logback', 'logging-monitoring-observability', 354, false),
('SLIs, SLOs & SLAs', 'slis-slos-slas', 'logging-monitoring-observability', 355, false),
('Spring Boot Actuator Endpoints', 'spring-boot-actuator-endpoints', 'logging-monitoring-observability', 356, false),
('Structured Logging – JSON Logs', 'structured-logging', 'logging-monitoring-observability', 357, false),
('Atomic Classes – AtomicInteger, AtomicReference', 'atomic-classes', 'multithreading-concurrency', 358, false),
('CompletableFuture – thenApply, thenCompose, thenCombine', 'completablefuture-chaining', 'multithreading-concurrency', 359, false),
('CountDownLatch', 'countdownlatch', 'multithreading-concurrency', 360, false),
('CyclicBarrier', 'cyclicbarrier', 'multithreading-concurrency', 361, false),
('Deadlock', 'deadlock', 'multithreading-concurrency', 362, false),
('ExecutorService', 'executorservice', 'multithreading-concurrency', 363, false),
('Fork/Join Framework', 'fork-join-framework', 'multithreading-concurrency', 364, false),
('Future & CompletableFuture', 'future-completablefuture', 'multithreading-concurrency', 365, false),
('Livelock', 'livelock', 'multithreading-concurrency', 366, false),
('Race Conditions', 'race-conditions', 'multithreading-concurrency', 367, false),
('ReadWriteLock', 'readwritelock', 'multithreading-concurrency', 368, false),
('ReentrantLock', 'reentrantlock', 'multithreading-concurrency', 369, false),
('Semaphore', 'semaphore', 'multithreading-concurrency', 370, false),
('start() vs. run()', 'start-vs-run', 'multithreading-concurrency', 371, false),
('Starvation', 'starvation', 'multithreading-concurrency', 372, false),
('Structured Concurrency (Java 21)', 'structured-concurrency', 'multithreading-concurrency', 373, false),
('synchronized Keyword', 'synchronized-keyword', 'multithreading-concurrency', 374, false),
('Thread Lifecycle', 'thread-lifecycle', 'multithreading-concurrency', 375, false),
('Thread Safety', 'thread-safety', 'multithreading-concurrency', 376, false),
('Thread vs. Runnable vs. Callable', 'thread-vs-runnable-vs-callable', 'multithreading-concurrency', 377, false),
('ThreadLocal', 'threadlocal', 'multithreading-concurrency', 378, false),
('ThreadPool – FixedThreadPool, CachedThreadPool, ScheduledThreadPool', 'threadpool', 'multithreading-concurrency', 379, false),
('Virtual Threads – Project Loom (Java 21)', 'virtual-threads-loom', 'multithreading-concurrency', 380, false),
('volatile Keyword (Concurrency)', 'volatile-concurrency', 'multithreading-concurrency', 381, false),
('wait(), notify() & notifyAll()', 'wait-notify', 'multithreading-concurrency', 382, false),
('CDN Grundlagen', 'cdn-grundlagen', 'netzwerk-protokolle-grundlagen', 383, false),
('Cookies & Sessions', 'cookies-sessions', 'netzwerk-protokolle-grundlagen', 384, false),
('DNS Grundlagen', 'dns-grundlagen', 'netzwerk-protokolle-grundlagen', 385, false),
('Headers – Content-Type, Authorization, Cache-Control', 'headers', 'netzwerk-protokolle-grundlagen', 386, false),
('HTTP 1.1 vs. HTTP 2 vs. HTTP 3', 'http-versionen', 'netzwerk-protokolle-grundlagen', 387, false),
('IP-Adressen & Ports', 'ip-adressen-ports', 'netzwerk-protokolle-grundlagen', 388, false),
('Load Balancer Grundlagen', 'load-balancer', 'netzwerk-protokolle-grundlagen', 389, false),
('Request/Response Modell', 'request-response-modell', 'netzwerk-protokolle-grundlagen', 390, false),
('Reverse Proxy & NGINX', 'reverse-proxy-nginx', 'netzwerk-protokolle-grundlagen', 391, false),
('SSL/TLS Handshake Grundlagen', 'ssl-tls-handshake', 'netzwerk-protokolle-grundlagen', 392, false),
('Status Codes – 200, 201, 204, 301, 400, 401, 403, 404, 409, 500, 502, 503', 'status-codes-netz', 'netzwerk-protokolle-grundlagen', 393, false),
('TCP vs. UDP', 'tcp-vs-udp', 'netzwerk-protokolle-grundlagen', 394, false),
('Abstrakte Klasse vs. Interface – Wann was?', 'abstrakte-klasse-vs-interface', 'oop-objektorientierte-programmierung', 395, false),
('Abstrakte Klassen', 'abstrakte-klassen', 'oop-objektorientierte-programmierung', 396, false),
('Access Modifiers – private, protected, public, package-private', 'access-modifiers', 'oop-objektorientierte-programmierung', 397, false),
('Aggregation vs. Komposition', 'aggregation-vs-komposition', 'oop-objektorientierte-programmierung', 398, false),
('Constructor Chaining', 'constructor-chaining', 'oop-objektorientierte-programmierung', 399, false),
('Dependency Inversion', 'dependency-inversion', 'oop-objektorientierte-programmierung', 400, false),
('DRY Principle', 'dry-principle', 'oop-objektorientierte-programmierung', 401, false),
('Einfachvererbung vs. Mehrfachvererbung', 'einfachvererbung-vs-mehrfachvererbung', 'oop-objektorientierte-programmierung', 402, false),
('Encapsulation / Kapselung', 'encapsulation', 'oop-objektorientierte-programmierung', 403, false),
('Favor Composition over Inheritance', 'favor-composition', 'oop-objektorientierte-programmierung', 404, false),
('Functional Interfaces', 'functional-interfaces-oop', 'oop-objektorientierte-programmierung', 405, false),
('Interface Default Methods', 'interface-default-methods', 'oop-objektorientierte-programmierung', 406, false),
('Interface Static Methods', 'interface-static-methods', 'oop-objektorientierte-programmierung', 407, false),
('Interfaces', 'interfaces', 'oop-objektorientierte-programmierung', 408, false),
('KISS Principle', 'kiss-principle', 'oop-objektorientierte-programmierung', 409, false),
('Klassen & Objekte', 'klassen-objekte', 'oop-objektorientierte-programmierung', 410, false),
('Kohäsion & Kopplung', 'kohaesion-kopplung', 'oop-objektorientierte-programmierung', 411, false),
('Komposition vs. Vererbung', 'komposition-vs-vererbung', 'oop-objektorientierte-programmierung', 412, false),
('Konstruktoren – Default, Parameterized, Copy', 'konstruktoren', 'oop-objektorientierte-programmierung', 413, false),
('Law of Demeter', 'law-of-demeter', 'oop-objektorientierte-programmierung', 414, false),
('Liskov Substitution Principle', 'liskov-substitution', 'oop-objektorientierte-programmierung', 415, false),
('Method Overloading', 'method-overloading', 'oop-objektorientierte-programmierung', 416, false),
('Method Overriding', 'method-overriding', 'oop-objektorientierte-programmierung', 417, false),
('Polymorphismus – Compile-Time vs. Runtime', 'polymorphismus', 'oop-objektorientierte-programmierung', 418, false),
('SOLID Prinzipien', 'solid-prinzipien', 'oop-objektorientierte-programmierung', 419, false),
('Tell Don''t Ask', 'tell-dont-ask', 'oop-objektorientierte-programmierung', 420, false),
('this & super Keyword', 'this-super-keyword', 'oop-objektorientierte-programmierung', 421, false),
('Vererbung (Inheritance)', 'vererbung', 'oop-objektorientierte-programmierung', 422, false),
('YAGNI Principle', 'yagni-principle', 'oop-objektorientierte-programmierung', 423, false),
('Decompose Conditional', 'decompose-conditional', 'refactoring', 424, false),
('Extract Class', 'extract-class', 'refactoring', 425, false),
('Extract Method', 'extract-method', 'refactoring', 426, false),
('Inline Variable & Method', 'inline-variable-method', 'refactoring', 427, false),
('Introduce Parameter Object', 'introduce-parameter-object', 'refactoring', 428, false),
('Move Method & Move Field', 'move-method-move-field', 'refactoring', 429, false),
('Rename – Variable, Method, Class', 'rename', 'refactoring', 430, false),
('Replace Conditional with Polymorphism', 'replace-conditional-polymorphism', 'refactoring', 431, false),
('Replace Inheritance with Delegation', 'replace-inheritance-delegation', 'refactoring', 432, false),
('Replace Magic Number with Constant', 'replace-magic-number-constant', 'refactoring', 433, false),
('Replace Temp with Query', 'replace-temp-with-query', 'refactoring', 434, false),
('Wann Refactoring – wann nicht?', 'wann-refactoring', 'refactoring', 435, false),
('API Security Best Practices', 'api-security-best-practices', 'security', 436, false),
('Authentication vs. Authorization', 'authentication-vs-authorization', 'security', 437, false),
('Cross-Site Request Forgery (CSRF)', 'csrf', 'security', 438, false),
('Cross-Site Scripting (XSS)', 'xss', 'security', 439, false),
('Dependency Vulnerability Scanning – OWASP, Snyk', 'dependency-vulnerability-scanning', 'security', 440, false),
('Hashing vs. Encryption', 'hashing-vs-encryption', 'security', 441, false),
('HTTPS & TLS', 'https-tls', 'security', 442, false),
('Input Validation & Sanitization', 'input-validation', 'security', 443, false),
('JWT – Aufbau & Validierung', 'jwt-aufbau', 'security', 444, false),
('OAuth2 Flows – Authorization Code & Client Credentials', 'oauth2-flows', 'security', 445, false),
('OWASP Top 10', 'owasp-top-10', 'security', 446, false),
('Principle of Least Privilege', 'least-privilege', 'security', 447, false),
('Rate Limiting & Throttling', 'rate-limiting-security', 'security', 448, false),
('Secrets Management', 'secrets-management', 'security', 449, false),
('SQL Injection', 'sql-injection', 'security', 450, false),
('Symmetric vs. Asymmetric Encryption', 'symmetric-vs-asymmetric-encryption', 'security', 451, false),
('API Gateway – Spring Cloud Gateway', 'api-gateway-spring-cloud', 'spring-framework-spring-boot', 452, false),
('API Versioning Strategien', 'api-versioning', 'spring-framework-spring-boot', 453, false),
('application.properties vs. application.yml', 'application-properties-yml', 'spring-framework-spring-boot', 454, false),
('Auditing – @CreatedDate, @LastModifiedDate', 'auditing-createddate', 'spring-framework-spring-boot', 455, false),
('Authentication & Authorization (Spring Security)', 'authentication-spring-security', 'spring-framework-spring-boot', 456, false),
('@Autowired', 'autowired', 'spring-framework-spring-boot', 457, false),
('Bean Lifecycle', 'bean-lifecycle', 'spring-framework-spring-boot', 458, false),
('Bean Scopes – Singleton, Prototype, Request, Session', 'bean-scopes', 'spring-framework-spring-boot', 459, false),
('JPA Beziehungen – @OneToOne, @OneToMany, @ManyToMany', 'beziehungen-jpa', 'spring-framework-spring-boot', 460, false),
('Cascade Types', 'cascade-types', 'spring-framework-spring-boot', 461, false),
('Circuit Breaker mit Resilience4j', 'circuit-breaker-resilience4j', 'spring-framework-spring-boot', 462, false),
('CommandLineRunner & ApplicationRunner', 'commandlinerunner', 'spring-framework-spring-boot', 463, false),
('@Component, @Service, @Repository, @Controller', 'component-service-repository-controller', 'spring-framework-spring-boot', 464, false),
('@Conditional', 'conditional', 'spring-framework-spring-boot', 465, false),
('Config Server', 'config-server', 'spring-framework-spring-boot', 466, false),
('@Configuration & @Bean', 'configuration-bean', 'spring-framework-spring-boot', 467, false),
('Content Negotiation', 'content-negotiation', 'spring-framework-spring-boot', 468, false),
('CORS Konfiguration', 'cors-konfiguration', 'spring-framework-spring-boot', 469, false),
('CORS & Security', 'cors-security', 'spring-framework-spring-boot', 470, false),
('CSRF Protection (Spring)', 'csrf-protection', 'spring-framework-spring-boot', 471, false),
('Dependency Injection – Constructor, Setter, Field', 'dependency-injection-spring', 'spring-framework-spring-boot', 472, false),
('Derived Query Methods', 'derived-query-methods', 'spring-framework-spring-boot', 473, false),
('Dirty Read, Non-Repeatable Read & Phantom Read', 'dirty-read-phantom-read', 'spring-framework-spring-boot', 474, false),
('Distributed Tracing – Micrometer Tracing & Zipkin', 'distributed-tracing-spring', 'spring-framework-spring-boot', 475, false),
('Embedded Server – Tomcat & Undertow', 'embedded-server', 'spring-framework-spring-boot', 476, false),
('Entity Mapping – @Entity, @Table, @Column, @Id', 'entity-mapping', 'spring-framework-spring-boot', 477, false),
('Externalized Configuration', 'externalized-configuration', 'spring-framework-spring-boot', 478, false),
('FetchType – LAZY vs. EAGER', 'fetchtype-lazy-eager', 'spring-framework-spring-boot', 479, false),
('Flyway & Liquibase – Database Migrations', 'flyway-liquibase', 'spring-framework-spring-boot', 480, false),
('Global Exception Handling – @ControllerAdvice & @ExceptionHandler', 'global-exception-handling', 'spring-framework-spring-boot', 481, false),
('HATEOAS', 'hateoas', 'spring-framework-spring-boot', 482, false),
('Health Checks – Readiness & Liveness Probes', 'health-checks-spring', 'spring-framework-spring-boot', 483, false),
('Inversion of Control (IoC)', 'ioc', 'spring-framework-spring-boot', 484, false),
('Isolation Levels in Spring – READ_COMMITTED, REPEATABLE_READ, SERIALIZABLE', 'isolation-levels-spring', 'spring-framework-spring-boot', 485, false),
('JpaRepository, CrudRepository & PagingAndSortingRepository', 'jpa-repository', 'spring-framework-spring-boot', 486, false),
('JPA vs. Hibernate vs. Spring Data JPA', 'jpa-vs-hibernate', 'spring-framework-spring-boot', 487, false),
('JWT Authentication (Spring Security)', 'jwt-authentication-spring', 'spring-framework-spring-boot', 488, false),
('Load Balancing (Spring Cloud)', 'load-balancing-spring', 'spring-framework-spring-boot', 489, false),
('Method Security – @PreAuthorize, @Secured', 'method-security', 'spring-framework-spring-boot', 490, false),
('N+1 Problem Lösungen – JOIN FETCH, @EntityGraph, Batch Size', 'n-plus-1-loesungen', 'spring-framework-spring-boot', 491, false),
('N+1 Problem', 'n-plus-1-problem', 'spring-framework-spring-boot', 492, false),
('OAuth2 & OpenID Connect (Spring)', 'oauth2-openid-spring', 'spring-framework-spring-boot', 493, false),
('Optimistic Locking – @Version', 'optimistic-locking', 'spring-framework-spring-boot', 494, false),
('Orphan Removal', 'orphan-removal', 'spring-framework-spring-boot', 495, false),
('Pagination & Sorting (Spring Data)', 'pagination-sorting', 'spring-framework-spring-boot', 496, false),
('PasswordEncoder & BCrypt', 'passwordencoder-bcrypt', 'spring-framework-spring-boot', 497, false),
('@PathVariable, @RequestParam, @RequestBody, @RequestHeader', 'pathvariable-requestparam', 'spring-framework-spring-boot', 498, false),
('Pessimistic Locking', 'pessimistic-locking', 'spring-framework-spring-boot', 499, false),
('Primary Key Generation – AUTO, IDENTITY, SEQUENCE, TABLE', 'primary-key-generation', 'spring-framework-spring-boot', 500, false),
('@Primary', 'primary-annotation', 'spring-framework-spring-boot', 501, false),
('Problem Detail – RFC 7807', 'problem-detail', 'spring-framework-spring-boot', 502, false),
('@Profile (Spring)', 'profile-spring', 'spring-framework-spring-boot', 503, false),
('Projections – Interface-based & Class-based', 'projections', 'spring-framework-spring-boot', 504, false),
('Propagation Levels – REQUIRED, REQUIRES_NEW, NESTED', 'propagation-levels', 'spring-framework-spring-boot', 505, false),
('@Qualifier', 'qualifier', 'spring-framework-spring-boot', 506, false),
('@Query – JPQL & Native', 'query-jpql-native', 'spring-framework-spring-boot', 507, false),
('Request Validation – @Valid, @NotNull, @Size, Custom Validators', 'request-validation', 'spring-framework-spring-boot', 508, false),
('@RequestMapping, @GetMapping, @PostMapping usw.', 'requestmapping-getmapping', 'spring-framework-spring-boot', 509, false),
('ResponseEntity', 'responseentity', 'spring-framework-spring-boot', 510, false),
('@ResponseStatus', 'responsestatus', 'spring-framework-spring-boot', 511, false),
('REST Best Practices (Spring)', 'rest-best-practices-spring', 'spring-framework-spring-boot', 512, false),
('@RestController vs. @Controller', 'restcontroller-vs-controller', 'spring-framework-spring-boot', 513, false),
('RESTful API Design – Ressourcen, HTTP-Verben, Statuscodes', 'restful-api-design', 'spring-framework-spring-boot', 514, false),
('Role-Based Access Control (Spring Security)', 'role-based-access-control', 'spring-framework-spring-boot', 515, false),
('@Scheduled', 'scheduled', 'spring-framework-spring-boot', 516, false),
('Second Level Cache – EHCache & Hazelcast', 'second-level-cache', 'spring-framework-spring-boot', 517, false),
('SecurityFilterChain', 'securityfilterchain', 'spring-framework-spring-boot', 518, false),
('Service Discovery – Eureka', 'service-discovery-eureka', 'spring-framework-spring-boot', 519, false),
('Service-to-Service Communication – RestClient, WebClient, OpenFeign', 'service-to-service-communication', 'spring-framework-spring-boot', 520, false),
('Specifications & Criteria API', 'specifications-criteria-api', 'spring-framework-spring-boot', 521, false),
('Spring ApplicationContext', 'spring-applicationcontext', 'spring-framework-spring-boot', 522, false),
('Spring Boot Actuator', 'spring-boot-actuator', 'spring-framework-spring-boot', 523, false),
('Spring Boot Auto-Configuration', 'spring-boot-auto-configuration', 'spring-framework-spring-boot', 524, false),
('Spring Boot DevTools', 'spring-boot-devtools', 'spring-framework-spring-boot', 525, false),
('Spring Boot Logging – SLF4J & Logback', 'spring-boot-logging', 'spring-framework-spring-boot', 526, false),
('Spring Boot Profiles', 'spring-boot-profiles', 'spring-framework-spring-boot', 527, false),
('Spring Boot Starter', 'spring-boot-starter', 'spring-framework-spring-boot', 528, false),
('Spring Data JDBC vs. Spring Data JPA', 'spring-data-jdbc-vs-jpa', 'spring-framework-spring-boot', 529, false),
('Spring Events – ApplicationEvent', 'spring-events', 'spring-framework-spring-boot', 530, false),
('Spring Expression Language (SpEL)', 'spring-expression-language', 'spring-framework-spring-boot', 531, false),
('Spring Security mit Spring Boot 3.x Konfiguration', 'spring-security-3x', 'spring-framework-spring-boot', 532, false),
('Structured Logging (Spring)', 'structured-logging-spring', 'spring-framework-spring-boot', 533, false),
('Swagger / OpenAPI mit springdoc-openapi', 'swagger-springdoc', 'spring-framework-spring-boot', 534, false),
('@Transactional – Transaction Management', 'transactional', 'spring-framework-spring-boot', 535, false),
('UserDetailsService', 'userdetailsservice', 'spring-framework-spring-boot', 536, false),
('@Value', 'value-annotation', 'spring-framework-spring-boot', 537, false),
('Warum Constructor Injection bevorzugt?', 'warum-constructor-injection', 'spring-framework-spring-boot', 538, false),
('AAA Pattern – Arrange, Act, Assert', 'aaa-pattern', 'testing', 539, false),
('ArgumentCaptor', 'argumentcaptor', 'testing', 540, false),
('AssertJ', 'assertj', 'testing', 541, false),
('BDD Style Testing – Given, When, Then', 'bdd-given-when-then', 'testing', 542, false),
('Contract Testing', 'contract-testing', 'testing', 543, false),
('End-to-End Testing', 'end-to-end-testing', 'testing', 544, false),
('Integration Testing', 'integration-testing', 'testing', 545, false),
('JUnit 5 Annotations – @Test, @BeforeEach, @Nested, @ParameterizedTest', 'junit5-annotations', 'testing', 546, false),
('JUnit 5 Assertions', 'junit5-assertions', 'testing', 547, false),
('JUnit 5 Grundlagen', 'junit5-grundlagen', 'testing', 548, false),
('@Mock, @InjectMocks, @Spy', 'mock-injectmocks-spy', 'testing', 549, false),
('Mocking vs. Stubbing vs. Spying', 'mocking-vs-stubbing-vs-spying', 'testing', 550, false),
('Mockito Grundlagen', 'mockito-grundlagen', 'testing', 551, false),
('MockMvc (Spring)', 'mockmvc', 'testing', 552, false),
('Mutation Testing – PIT', 'mutation-testing', 'testing', 553, false),
('Parameterized Tests', 'parameterized-tests', 'testing', 554, false),
('@SpringBootTest vs. @WebMvcTest vs. @DataJpaTest', 'springboottest-vs-webmvctest', 'testing', 555, false),
('TDD – Test Driven Development', 'tdd', 'testing', 556, false),
('Test Naming Conventions', 'test-naming-conventions', 'testing', 557, false),
('Testabdeckung & Code Coverage', 'testabdeckung-coverage', 'testing', 558, false),
('Testbare Klassen schreiben – Dependency Injection', 'testbare-klassen', 'testing', 559, false),
('Testcontainers (Testing)', 'testcontainers-testing', 'testing', 560, false),
('Testpyramide', 'testpyramide', 'testing', 561, false),
('Unit Testing', 'unit-testing', 'testing', 562, false),
('verify() in Mockito', 'verify-mockito', 'testing', 563, false),
('Was testen – was nicht?', 'was-testen-was-nicht', 'testing', 564, false),
('when/thenReturn vs. doReturn/when', 'when-thenreturn-vs-doreturn', 'testing', 565, false),
('WireMock (Testing)', 'wiremock-testing', 'testing', 566, false),
('Branching & Merging', 'branching-merging', 'versionskontrolle-git', 567, false),
('Cherry-Pick', 'cherry-pick', 'versionskontrolle-git', 568, false),
('Code Review Best Practices', 'code-review-best-practices', 'versionskontrolle-git', 569, false),
('Conventional Commits', 'conventional-commits', 'versionskontrolle-git', 570, false),
('Feature Branches', 'feature-branches', 'versionskontrolle-git', 571, false),
('git bisect', 'git-bisect', 'versionskontrolle-git', 572, false),
('Git Flow vs. Trunk-Based Development', 'git-flow-vs-trunk-based', 'versionskontrolle-git', 573, false),
('Git Grundbefehle – init, clone, add, commit, push, pull', 'git-grundbefehle', 'versionskontrolle-git', 574, false),
('.gitignore', 'gitignore', 'versionskontrolle-git', 575, false),
('Interactive Rebase', 'interactive-rebase', 'versionskontrolle-git', 576, false),
('Merge Conflicts lösen', 'merge-conflicts', 'versionskontrolle-git', 577, false),
('Merge vs. Rebase', 'merge-vs-rebase', 'versionskontrolle-git', 578, false),
('Pull Requests & Merge Requests', 'pull-requests', 'versionskontrolle-git', 579, false),
('Semantic Versioning mit Git Tags', 'semantic-versioning-git', 'versionskontrolle-git', 580, false),
('Squash Commits', 'squash-commits', 'versionskontrolle-git', 581, false),
('git stash', 'stash', 'versionskontrolle-git', 582, false);
